### ISSUE TITLE
Demos für das Labor

### ISSUE THREAD

**Issue by MBrill** [VRLAB-HSKL/DesktopXR#14]
Wir schauen nochmal alle Projektarbeiten durch und entscheiden, ob wir sie in die Liste der Demos aufnehmen, die wir beim Tag des offenen Campus oder anderen Gelegenheiten vorführen.

- Wir stellen sicher, dass sie auf den neuen Rechnern laufen.
- Wir verwenden die auf allen Rechnern installierte Unity 2019 Version.

Kandidaten:
- Messekonfigurator
- Luftschiff
- MiniWorlds (VIU)
- Football mit Sprachsteuerung
- Desktop XR
- Baseball
- Virtual Science Lab
- Fluid Flow Vis
- Visualisierung von georeferenzierten Daten

**Comment by fkalweit** [comment]
Ich würde folgende Projekte vorstellen:
- Luftschiff (einfach und schnell erklärt)
- MiniWorlds (mehrere Demos in einem)
- Baseball (schnell erklärt und ich denke jeder weiß was zu tun ist. Muss aber glaub ich noch gedreht werden, dass es wieder in den Raum passt)

Wenn wir mehr als eine Brille benutzen noch Desktop XR
