### ISSUE TITLE
Sprachsteuerung

### ISSUE THREAD

**Issue by sebmorsch** [VRLAB-HSKL/DesktopXR#7]
## Kurzbeschreibung Sprachsteuerung
Mit der Sprachsteuerung werden Szenenwechsel und bereits vorhandene Anwendungsmodule um eine Interaktionsmöglichkeit erweitert. Des Weiteren soll der Anwender, mithilfe der Sprachsteuerung, zwischen Controller und Gestenerkennung (Leap Motion) wechseln können.
Die Sprachsteuerung wird, wie bereits bei bekannten Produkten in zwei Befehlsarten, Aktivierungswort und Befehl, unterteilt. Diese Befehlsarten werden in einer XML oder JSON-Datei im Projektordner hinterlegt. So ist es möglich die Befehle zu ändern ohne das Projekt neu bauen zu müssen.

**Comment by MBrill** [comment]
Wenn ich es richtig sehe gibt es bereits eine Datei, in der wir initialisieren können. Wir haben in einer anderen Masterarbeit 2017 einen kompletten XML-Parser für den gleichen Zweck implementiert, den wir uns ansehen und in das Projekt integrieren sollten. Den parser findet man im Wiki im OLAT-Kurs AVR. Dort füge ich dich auch hinzu ...

Bevor wir Sprachsteuerung angehen sollten wir schauen, dass wir einige Beispiele mit der LeapMotion realisieren.

**Comment by MBrill** [comment]
Wir konzentrieren uns auf Windows.

**Comment by MBrill** [comment]
Wir haben diese Richtung in der Masterarbeit von Sebastian nicht mehr weiter verfolgt, da wir auf die Focus Plus gewechselt auf Grund der covid-19 krise. Auf Android bedeutet Spracherkennung Kontakt mit Samsung Google-Servern. Wir haben uns dagegen entschieden, dies auszunutzen.
