### ISSUE TITLE
Platzierung der LeapMotion auf dem Tisch

### ISSUE THREAD

**Issue by MBrill** [VRLAB-HSKL/DesktopXR#9]
Bestimmung einer guten Platzierung des LeapMotion-Sensors auf dem Tisch.

Kriterien:
- Die Erkennung von Gesten sollte möglichst stabil möglich sein.
- Die User dürfen den Sensor möglichst nicht berühren, da das zu Irritationen führen könnte. Eventuell den Sensor virtuell rendern, wenn es nicht anders geht.

**Comment by MBrill** [comment]
Damit können wir nicht bis zur Abgabe von Sebastian warten :-)

**Comment by sebmorsch** [comment]
### Hand-Tracking
Für das Hand-Tracking habe ich ja bereits eine E-Mail geschrieben. Bräuchten einen 3D-Druck der Halterung. Fände es sehr interessant die beiden Hand-Tracking "Arten" zu vergleichen. (VivePro Hand Tracking SDK mit Leap Motion)
Gerade wenn die Anwendung auch auf Androidgeräten laufen soll, sollten wir auf jeden Fall eine solche Halterung drucken. Die andere Art des Hand-Trackings funktioniert nur mit der Vive Pro. 
###Gesten-Erkennung
Hier würde ich die Leap-Motion direkt vor dem Benutzer mittig auf dem Tisch platzieren. Der Nutzer muss die Hände direkt, möglichst 30 cm,  über der Leap Motion platzieren. Auch die Visualisierung des Sensors ist meiner Meinung nach äußerst wichtig. Nutzer könnten eventuell zurückgelehnt im Stuhl Gesten verwednen. Dies ist allerdings nicht möglich. Mit einem Sensormodel werden sie immer daran erinnert, wo sich der Sensor befindet. 

###Leap Motion Field of View
the Leap Motion Controller’s field of view (FOV) is 150 degrees wide and 120 degrees deep (averaging 135 degrees
Quelle: http://blog.leapmotion.com/12-faqs-vr-developer-mount/

![leapmotion_fieldofview](https://user-images.githubusercontent.com/43551654/74660889-42273a00-5197-11ea-9e1f-ba67cda418b5.PNG)

Bildquelle: http://blog.leapmotion.com/hardware-to-software-how-does-the-leap-motion-controller-work/
